# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-15 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_permission_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='优先级'),
        ),
    ]
