 # -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=32)),
                ('score', models.DecimalField(decimal_places=0, max_digits=3)),
                ('my_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app01.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('classes', models.ManyToManyField(related_name='teacher', to='app01.Classes')),
            ],
        ),
    ]
