# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 08:43
from __future__ import unicode_literals

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190624_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', app01.models.MyCharField(max_length=20)),
            ],
        ),
    ]
