# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='addr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
