# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20190624_0944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('birth', 'age')]),
        ),
    ]
