# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='权重'),
        ),
    ]
