# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
