# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_person_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='addr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_column='name', max_length=32),
        ),
    ]
