# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20190624_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='addr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地址'),
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
