# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-15 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_permission_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='weight',
        ),
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='优先级'),
        ),
    ]
