# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20190715_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='url别名'),
            preserve_default=False,
        ),
    ]
