# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-12 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_permission_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图标'),
        ),
    ]
