# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default=False, max_length=32),
        ),
    ]
