# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190625_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Publisher'),
            preserve_default=False,
        ),
    ]
