# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_auto_20190716_0832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set([('menu', 'parent')]),
        ),
    ]
