# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_auto_20190716_2147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set([]),
        ),
    ]
