# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0013_auto_20190716_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='权重'),
        ),
    ]
