# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190625_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='xxx', to='app01.Publisher'),
        ),
    ]
